type CryptoType = {
    id: number,
    name: string,
    symbol: string,
    category: string,
    description: string,
    slug: string,
    logo: string,
    subreddit: string,
    notice: string,
    tags: [],
    'tag-names': [],
    'tag-groups': [],
    urls: object[],
    platform: object[],
    date_added: string,
    twitter_username: string,
    is_hidden: 0,
    date_launched: any,
    contract_address: [],
    self_reported_circulating_supply: any,
    self_reported_tags: any,
    self_reported_market_cap: any,
}

export default CryptoType
